### import dataset and update columnnames

In [1]:
import pandas as pd
data = pd.read_csv('../Jan 2021 Data - Viz5 Gender Inequality and HIVAIDS.csv', encoding = 'unicode_escape', engine ='python')
#ecoding='unicode_escape' has to be used to enable opening
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2640 entries, 0 to 2639
Data columns (total 10 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   Country                                                                         2640 non-null   object
 1   UNICEF Region                                                                   2640 non-null   object
 2   Year                                                                            2640 non-null   int64
 3   Sex                                                                             2640 non-null   object
 4   Age                                                                             2640 non-null   object
 5   Estimated incidence rate of new HIV infection per 1 000 uninfected population   2520 non-null   float64
 6   Estimated number of annual AIDS related deaths                                  2580 non-null   float64
 7   Estimated number of annual new HIV infections                                   2520 non-null   float64
 8   Estimated number of people living with HIV                                      2640 non-null   int64
 9   Estimated rate of annual AIDS related deaths  per 100 000 population            2580 non-null   float64
dtypes: float64(4), int64(2), object(4)
memory usage: 206.4+ KB

In [154]:
data.head(10)

,Country,Region,Year,Sex,Age,Estimated rate new HIV infection per 1000 people,Estimated annual AIDS related deaths,Estimated annual new HIV infections,Estimated number of people living with HIV,Estimated rate annual AIDS related deaths per 100000 people
0,Angola,Eastern and Southern Africa,1990,Female,Age 10-19,0.64,100.0,500.0,860,0.36
1,Angola,Eastern and Southern Africa,1990,Male,Age 10-19,0.15,100.0,100.0,200,0.07
2,Angola,Eastern and Southern Africa,1991,Female,Age 10-19,0.75,100.0,500.0,1100,0.42
3,Angola,Eastern and Southern Africa,1991,Male,Age 10-19,0.17,100.0,200.0,500,0.14
4,Angola,Eastern and Southern Africa,1992,Female,Age 10-19,0.88,100.0,590.0,1300,0.54
5,Angola,Eastern and Southern Africa,1992,Male,Age 10-19,0.19,100.0,200.0,500,0.14
6,Angola,Eastern and Southern Africa,1993,Female,Age 10-19,1.04,100.0,720.0,1600,0.65
7,Angola,Eastern and Southern Africa,1993,Male,Age 10-19,0.23,100.0,200.0,500,0.20
8,Angola,Eastern and Southern Africa,1994,Female,Age 10-19,1.19,100.0,850.0,2000,0.75
9,Angola,Eastern and Southern Africa,1994,Male,Age 10-19,0.26,100.0,200.0,500,0.25

In [156]:
len(data['Country'].value_counts())

44

In [75]:
data.columns = ['Country', 'Region', 'Year', 'Sex', 'Age',
       'Estimated rate new HIV infection per 1000 people',
       'Estimated annual AIDS related deaths',
       'Estimated annual new HIV infections',
       'Estimated number of people living with HIV',
       'Estimated rate annual AIDS related deaths per 100000 people']

In [78]:
data.head(4)

,Country,Region,Year,Sex,Age,Estimated rate new HIV infection per 1000 people,Estimated annual AIDS related deaths,Estimated annual new HIV infections,Estimated number of people living with HIV,Estimated rate annual AIDS related deaths per 100000 people
0,Angola,Eastern and Southern Africa,1990,Female,Age 10-19,0.64,100.0,500.0,860,0.36
1,Angola,Eastern and Southern Africa,1990,Male,Age 10-19,0.15,100.0,100.0,200,0.07
2,Angola,Eastern and Southern Africa,1991,Female,Age 10-19,0.75,100.0,500.0,1100,0.42
3,Angola,Eastern and Southern Africa,1991,Male,Age 10-19,0.17,100.0,200.0,500,0.14

### calculate mean values per year for female and male
outcoming dataframe: "mean_per_year_and_sex"

In [93]:
mean_per_year_and_sex = data.groupby(by=['Year', 'Sex'], as_index=False).mean().round(3)
mean_per_year_and_sex[['Country', 'Region', 'Age']] = ['Mean_per_year_and_sex', 'None', 'Age 10-19']
mean_per_year_and_sex = mean_per_year_and_sex.sort_values(by=['Year','Sex'])
mean_per_year_and_sex.head(3)

,Year,Sex,Estimated rate new HIV infection per 1000 people,Estimated annual AIDS related deaths,Estimated annual new HIV infections,Estimated number of people living with HIV,Estimated rate annual AIDS related deaths per 100000 people,Country,Region,Age
0,1990,Female,6.546,139.535,3707.143,7933.409,3.394,Mean_per_year_and_sex,None,Age 10-19
1,1990,Male,1.788,100.000,1061.429,1982.727,0.843,Mean_per_year_and_sex,None,Age 10-19
2,1991,Female,7.426,141.860,4221.667,9429.318,4.217,Mean_per_year_and_sex,None,Age 10-19

### calculate mean for each year
outcoming dataframe:"mean_per_year"

In [81]:
mean_per_year = data.groupby(by='Year', as_index=False).mean().round(3)

mean_per_year[['Country', 'Region', 'Age', 'Sex']] = ['Mean_per_year', 'None', 'Age 10-19', 'Mean']
mean_per_year.head(4)

,Year,Estimated rate new HIV infection per 1000 people,Estimated annual AIDS related deaths,Estimated annual new HIV infections,Estimated number of people living with HIV,Estimated rate annual AIDS related deaths per 100000 people,Country,Region,Age,Sex
0,1990,4.167,119.767,2384.286,4958.068,2.118,Mean_per_year,None,Age 10-19,Mean
1,1991,4.686,122.093,2692.738,5847.386,2.662,Mean_per_year,None,Age 10-19,Mean
2,1992,5.096,138.372,2980.476,6696.477,3.227,Mean_per_year,None,Age 10-19,Mean
3,1993,5.457,146.512,3192.500,7465.455,3.870,Mean_per_year,None,Age 10-19,Mean

### calculate the differnce between female and total average and male and total average

#### diff female- average
outcoming dataframe: "diff_female_mean"

In [122]:
#concatinate df mean_per_year and mean_per_year_and_sex with 'female' to check, if the output is the expected:

temp = pd.concat([mean_per_year, mean_per_year_and_sex.loc[mean_per_year_and_sex['Sex']== 'Female']])\
.sort_values(by=['Year', 'Country'])
temp.head(4)

,Year,Estimated rate new HIV infection per 1000 people,Estimated annual AIDS related deaths,Estimated annual new HIV infections,Estimated number of people living with HIV,Estimated rate annual AIDS related deaths per 100000 people,Country,Region,Age,Sex
0,1990,4.167,119.767,2384.286,4958.068,2.118,Mean_per_year,None,Age 10-19,Mean
0,1990,6.546,139.535,3707.143,7933.409,3.394,Mean_per_year_and_sex,None,Age 10-19,Female
1,1991,4.686,122.093,2692.738,5847.386,2.662,Mean_per_year,None,Age 10-19,Mean
2,1991,7.426,141.860,4221.667,9429.318,4.217,Mean_per_year_and_sex,None,Age 10-19,Female

In [121]:
#concatinate df mean_per_year and the 'female' rows of mean_per_year_and_sex 
# and group by year to calculate difference between mean and female numbers

diff_female_mean = pd.concat([mean_per_year, mean_per_year_and_sex.loc[mean_per_year_and_sex['Sex']== 'Female']])\
.sort_values(by=['Year','Country'])[['Year','Estimated rate new HIV infection per 1000 people','Estimated annual AIDS related deaths','Estimated annual new HIV infections','Estimated number of people living with HIV','Estimated rate annual AIDS related deaths per 100000 people']]\
.groupby('Year')\
.diff().dropna()
diff_female_mean[['Country', 'Region', 'Age', 'Sex']] = ['Diff_female_mean', 'None', 'Age 10-19', 'Diff_female_mean']

diff_female_mean = diff_female_mean.reset_index(drop=True)
diff_female_mean['Year'] = mean_per_year['Year']
diff_female_mean.head(4)

,Estimated rate new HIV infection per 1000 people,Estimated annual AIDS related deaths,Estimated annual new HIV infections,Estimated number of people living with HIV,Estimated rate annual AIDS related deaths per 100000 people,Country,Region,Age,Sex,Year
0,2.379,19.768,1322.857,2975.341,1.276,Diff_female_mean,None,Age 10-19,Diff_female_mean,1990
1,2.740,19.767,1528.929,3581.932,1.555,Diff_female_mean,None,Age 10-19,Diff_female_mean,1991
2,3.063,33.721,1744.286,4171.478,1.843,Diff_female_mean,None,Age 10-19,Diff_female_mean,1992
3,3.354,39.535,1906.310,4663.636,2.133,Diff_female_mean,None,Age 10-19,Diff_female_mean,1993

#### diff male-mean

In [8]:
#concatinate df mean_per_year and mean_per_year_and_sex with 'male' to check, if the output is the expected:
pd.concat([mean_per_year, mean_per_year_and_sex.loc[mean_per_year_and_sex['Sex']== 'Male']])\
.sort_values(by=['Year', 'Country']).head(6)

,Year,Estimated rate new HIV infection per 1000 people,Estimated annual AIDS related deaths,Estimated annual new HIV infections,Estimated number of people living with HIV,Estimated rate annual AIDS related deaths per 100000 people,Country,Region,Age,Sex
0,1990,4.167,119.767,2384.286,4958.068,2.118,Mean_per_year,None,Age 10-19,Mean
1,1990,1.788,100.000,1061.429,1982.727,0.843,Mean_per_year_and_sex,None,Age 10-19,Male
1,1991,4.686,122.093,2692.738,5847.386,2.662,Mean_per_year,None,Age 10-19,Mean
3,1991,1.946,102.326,1163.810,2265.455,1.108,Mean_per_year_and_sex,None,Age 10-19,Male
2,1992,5.096,138.372,2980.476,6696.477,3.227,Mean_per_year,None,Age 10-19,Mean
5,1992,2.034,104.651,1236.190,2525.000,1.384,Mean_per_year_and_sex,None,Age 10-19,Male

In [123]:
#concatinate df mean_per_year and the 'female' rows of mean_per_year_and_sex 
# and group by year to calculate difference between mean and male numbers

diff_male_mean = pd.concat([mean_per_year, mean_per_year_and_sex.loc[mean_per_year_and_sex['Sex']== 'Male']])\
.sort_values(by=['Year','Country'])[['Year','Estimated rate new HIV infection per 1000 people','Estimated annual AIDS related deaths','Estimated annual new HIV infections','Estimated number of people living with HIV','Estimated rate annual AIDS related deaths per 100000 people']]\
.groupby('Year', as_index=False)\
.diff().dropna()
diff_male_mean[['Country', 'Region', 'Age', 'Sex']] = ['Diff_male_mean', 'None', 'Age 10-19', 'Diff_male_mean']

diff_male_mean = diff_male_mean.reset_index(drop=True)
diff_male_mean['Year'] = mean_per_year['Year']
diff_male_mean.head(4)

,Estimated rate new HIV infection per 1000 people,Estimated annual AIDS related deaths,Estimated annual new HIV infections,Estimated number of people living with HIV,Estimated rate annual AIDS related deaths per 100000 people,Country,Region,Age,Sex,Year
0,-2.379,-19.767,-1322.857,-2975.341,-1.275,Diff_male_mean,None,Age 10-19,Diff_male_mean,1990
1,-2.740,-19.767,-1528.928,-3581.931,-1.554,Diff_male_mean,None,Age 10-19,Diff_male_mean,1991
2,-3.062,-33.721,-1744.286,-4171.477,-1.843,Diff_male_mean,None,Age 10-19,Diff_male_mean,1992
3,-3.355,-39.535,-1906.310,-4663.637,-2.133,Diff_male_mean,None,Age 10-19,Diff_male_mean,1993

### difference between female and male each year

#### difference-substract
outcoming dataframe "difference_female_male"

In [126]:
print(mean_per_year_and_sex.columns)
mean_per_year_and_sex.head(4)

Index(['Year', 'Sex', 'Estimated rate new HIV infection per 1000 people',
       'Estimated annual AIDS related deaths',
       'Estimated annual new HIV infections',
       'Estimated number of people living with HIV',
       'Estimated rate annual AIDS related deaths per 100000 people',
       'Country', 'Region', 'Age'],
      dtype='object')

,Year,Sex,Estimated rate new HIV infection per 1000 people,Estimated annual AIDS related deaths,Estimated annual new HIV infections,Estimated number of people living with HIV,Estimated rate annual AIDS related deaths per 100000 people,Country,Region,Age
0,1990,Female,6.546,139.535,3707.143,7933.409,3.394,Mean_per_year_and_sex,None,Age 10-19
1,1990,Male,1.788,100.000,1061.429,1982.727,0.843,Mean_per_year_and_sex,None,Age 10-19
2,1991,Female,7.426,141.860,4221.667,9429.318,4.217,Mean_per_year_and_sex,None,Age 10-19
3,1991,Male,1.946,102.326,1163.810,2265.455,1.108,Mean_per_year_and_sex,None,Age 10-19

In [134]:
difference_female_male = mean_per_year_and_sex\
.sort_values(by=['Year','Sex'])\
.groupby('Year',as_index=False)[['Estimated rate new HIV infection per 1000 people', 'Estimated annual AIDS related deaths','Estimated annual new HIV infections','Estimated number of people living with HIV', 'Estimated rate annual AIDS related deaths per 100000 people']].diff()

difference_female_male = difference_female_male.iloc[difference_female_male.index%2 == 1]
difference_female_male[['Country', 'Region', 'Age', 'Sex']] = ['Diff_female_male', 'None', 'Age 10-19', 'Diff_female_male']
difference_female_male = difference_female_male.reset_index(drop=True)
difference_female_male['Year'] = mean_per_year['Year']

difference_female_male.head(2)

,Estimated rate new HIV infection per 1000 people,Estimated annual AIDS related deaths,Estimated annual new HIV infections,Estimated number of people living with HIV,Estimated rate annual AIDS related deaths per 100000 people,Country,Region,Age,Sex,Year
0,-4.758,-39.535,-2645.714,-5950.682,-2.551,Diff_female_male,None,Age 10-19,Diff_female_male,1990
1,-5.480,-39.534,-3057.857,-7163.863,-3.109,Diff_female_male,None,Age 10-19,Diff_female_male,1991

#### difference-percentage
outcoming dataframes:
"percentage_of_female_to_male_per_year" and 
"percentage_of_male_to_female_per_year"

In [12]:
mean_per_year_and_sex.head(4)

,Year,Sex,Estimated rate new HIV infection per 1000 people,Estimated annual AIDS related deaths,Estimated annual new HIV infections,Estimated number of people living with HIV,Estimated rate annual AIDS related deaths per 100000 people,Country,Region,Age
0,1990,Female,6.546,139.535,3707.143,7933.409,3.394,Mean_per_year_and_sex,None,Age 10-19
1,1990,Male,1.788,100.000,1061.429,1982.727,0.843,Mean_per_year_and_sex,None,Age 10-19
2,1991,Female,7.426,141.860,4221.667,9429.318,4.217,Mean_per_year_and_sex,None,Age 10-19
3,1991,Male,1.946,102.326,1163.810,2265.455,1.108,Mean_per_year_and_sex,None,Age 10-19

In [135]:
#calculate percentage from female to male (female numbers/male numbers)
mean_per_year_and_sex = mean_per_year_and_sex.sort_values(by=['Year', 'Sex'])
percentage_of_female_to_male_per_year = get_percentage_from_row_above(mean_per_year_and_sex[['Estimated rate new HIV infection per 1000 people', 'Estimated annual AIDS related deaths','Estimated annual new HIV infections','Estimated number of people living with HIV','Estimated rate annual AIDS related deaths per 100000 people']])
percentage_of_female_to_male_per_year[['Country', 'Region', 'Age', 'Sex']] = ['Percentage_of_female_to_male', 'None', 'Age 10-19', 'Percentage_of_female_to_male']
percentage_of_female_to_male_per_year['Year'] = mean_per_year['Year']
percentage_of_female_to_male_per_year.head(4)

,Estimated rate new HIV infection per 1000 people,Estimated annual AIDS related deaths,Estimated annual new HIV infections,Estimated number of people living with HIV,Estimated rate annual AIDS related deaths per 100000 people,Country,Region,Age,Sex,Year
0,366.1,139.5,349.3,400.1,402.6,Percentage_of_female_to_male,None,Age 10-19,Percentage_of_female_to_male,1990
1,381.6,138.6,362.7,416.2,380.6,Percentage_of_female_to_male,None,Age 10-19,Percentage_of_female_to_male,1991
2,401.1,164.4,382.2,430.4,366.3,Percentage_of_female_to_male,None,Age 10-19,Percentage_of_female_to_male,1992
3,419.2,173.9,396.4,432.9,345.6,Percentage_of_female_to_male,None,Age 10-19,Percentage_of_female_to_male,1993

In [136]:
#calculate percentage between male and female (male numbers/female numbers)
mean_per_year_and_sex = mean_per_year_and_sex.sort_values(by=['Year', 'Sex'])
percentage_of_male_to_female_per_year = get_percentage_from_row_below(mean_per_year_and_sex[['Estimated rate new HIV infection per 1000 people', 'Estimated annual AIDS related deaths','Estimated annual new HIV infections','Estimated number of people living with HIV','Estimated rate annual AIDS related deaths per 100000 people']])
percentage_of_male_to_female_per_year[['Country', 'Region', 'Age', 'Sex']] = ['Percentage_of_male_to_female', 'None', 'Age 10-19', 'Percentage_of_male_to_female']
percentage_of_male_to_female_per_year['Year'] = mean_per_year['Year']
percentage_of_male_to_female_per_year.head(4)

,Estimated rate new HIV infection per 1000 people,Estimated annual AIDS related deaths,Estimated annual new HIV infections,Estimated number of people living with HIV,Estimated rate annual AIDS related deaths per 100000 people,Country,Region,Age,Sex,Year
0,0.273,0.717,0.286,0.250,0.248,Percentage_of_male_to_female,None,Age 10-19,Percentage_of_male_to_female,1990
1,0.262,0.721,0.276,0.240,0.263,Percentage_of_male_to_female,None,Age 10-19,Percentage_of_male_to_female,1991
2,0.249,0.608,0.262,0.232,0.273,Percentage_of_male_to_female,None,Age 10-19,Percentage_of_male_to_female,1992
3,0.239,0.575,0.252,0.231,0.289,Percentage_of_male_to_female,None,Age 10-19,Percentage_of_male_to_female,1993

In [45]:
def get_percentage_from_row_above(df):
    '''calculates percentage between the row above and the current 
    row for every second row- pecentage between female and male amount'''
    columns = df.columns
    temp_c = []
    df_percentage = pd.DataFrame()
    for c in columns:
        temp_l = []
        
        for l in range(0,len(df[c]),2):
            if l < len(df[c]):
                temp_l.append(round(df[c][l]/df[c][l+1], 3)*100)
        #temp_c.append(temp_l)
        df_percentage[c] = temp_l
    df_percentage.columns = df.columns
    return df_percentage

In [47]:
def get_percentage_from_row_below(df):
    columns = df.columns
    temp_c = []
    df_percentage = pd.DataFrame()
    for c in columns:
        temp_l = []
        
        for l in range(0,len(df[c]),2):
            if l <= len(df[c]):
                temp_l.append(round(df[c][l+1]/df[c][l], 3))
        #temp_c.append(temp_l)
        df_percentage[c] = temp_l
    df_percentage.columns = df.columns
    return df_percentage

### concat all dataframes and save to csv

In [143]:
data_and_total_numbers = pd.concat([data, mean_per_year_and_sex,mean_per_year,
                                    diff_female_mean, diff_male_mean, difference_female_male,
                                    percentage_of_male_to_female_per_year, percentage_of_female_to_male_per_year
                                   ])
data_and_total_numbers.to_csv('hiv_and_gender_inequality.csv')
data_and_total_numbers['Country'].value_counts()

Angola                              60
Somalia                             60
Burundi                             60
Malawi                              60
Namibia                             60
Niger                               60
Nigeria                             60
Rwanda                              60
Sudan                               60
Senegal                             60
Sierra Leone                        60
South Sudan                         60
Mozambique                          60
Eswatini                            60
Chad                                60
Togo                                60
United Republic of Tanzania         60
Uganda                              60
South Africa                        60
Zambia                              60
Zimbabwe                            60
Mean_per_year_and_sex               60
Mauritania                          60
Mauritius                           60
Mali                                60
Ethiopia                            60
Benin                               60
Burkina Faso                        60
Central African Republic            60
Côte d'Ivoire                       60
Cameroon                            60
Democratic Republic of the Congo    60
Congo                               60
Madagascar                          60
Eritrea                             60
Djibouti                            60
Gabon                               60
Ghana                               60
Guinea                              60
Gambia                              60
Guinea-Bissau                       60
Equatorial Guinea                   60
Kenya                               60
Liberia                             60
Lesotho                             60
Mean_per_year                       30
Diff_female_mean                    30
Diff_male_mean                      30
Diff_female_male                    30
Percentage_of_male_to_female        30
Percentage_of_female_to_male        30
Name: Country, dtype: int64